import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://127.0.0.1:8000/partner/login');
  await page.getByRole('link', { name: 'Regisztráljon partnerként' }).click();
  await page.getByRole('textbox', { name: 'Cég neve *' }).click();
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('D');
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('Demo ');
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('Demo K');
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('Demo Kft.');
  await page.getByRole('textbox', { name: 'Adószám' }).click();
  await page.getByRole('textbox', { name: 'Adószám' }).fill('12345678-1-26');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).click();
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('6760 ');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('6760 K');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('6760 Kistelek, ');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('6760 Kistelek, T');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('6760 Kistelek, Tisza utca 11.');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).click();
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).fill('S');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).fill('Simicz ');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).fill('Simicz Z');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).fill('Simicz Zalán');
  await page.getByRole('textbox', { name: 'Email cím *' }).click();
  await page.getByRole('textbox', { name: 'Email cím *' }).fill('zalansimicz@gmail.com');
  await page.getByRole('textbox', { name: 'Jelszó *' }).click();
  await page.getByRole('textbox', { name: 'Jelszó *' }).fill('12345678');
  await page.getByRole('textbox', { name: 'Jelszó megerősítése *' }).click();
  await page.getByRole('textbox', { name: 'Jelszó megerősítése *' }).fill('12345678');
  await page.getByRole('button', { name: ' Regisztráció' }).click();
});