import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://127.0.0.1:8000/partner/login');
  await page.getByRole('textbox', { name: 'Email cím' }).click();
  await page.getByRole('textbox', { name: 'Jelszó' }).click();
  await page.getByRole('button', { name: ' Bejelentkezés' }).click();
  await page.getByText('Jelszó').click();
  await page.getByRole('link', { name: 'Regisztráljon partnerként' }).click();
  await page.getByRole('textbox', { name: 'Cég neve *' }).click();
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('D');
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('Demo ');
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('Demo L');
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('Demo ');
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('Demo K');
  await page.getByRole('textbox', { name: 'Cég neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Cég neve *' }).fill('Demo Kft.');
  await page.getByRole('textbox', { name: 'Adószám' }).click();
  await page.getByRole('textbox', { name: 'Adószám' }).fill('12345678-1-26');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).click();
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('1234 ');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('1234 D');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('1234 Demo, ');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('1234 Demo, D');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Székhely / cím' }).fill('1234 Demo, Demo utca 1.');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).click();
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).fill('K');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).fill('Kiss ');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).fill('Kiss P');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Kapcsolattartó neve *' }).fill('Kiss Pista');
  await page.getByRole('textbox', { name: 'Email cím *' }).click();
  await page.getByRole('textbox', { name: 'Email cím *' }).fill('simiczzalan2005@gmail.com');
  await page.getByRole('textbox', { name: 'Jelszó *' }).click();
  await page.getByRole('textbox', { name: 'Jelszó *' }).fill('12345678');
  await page.getByRole('textbox', { name: 'Jelszó megerősítése *' }).click();
  await page.getByRole('textbox', { name: 'Jelszó megerősítése *' }).fill('12345678');
  await page.getByRole('button', { name: ' Regisztráció' }).click();
  await page.locator('div').nth(2).click();
});